import React, { useState, useEffect } from 'react';
import { Container, Row, Col, Button } from 'react-bootstrap';
import Card from 'react-bootstrap/Card';
import './Jeopardy.css';
import Question from './Question.jsx';
import { useSocket } from '../../../services/SocketContext';
import { useAuth } from '../../../services/AuthContext';

const JeopardyBoard = ({ selectorUsername }) => {
  const [gameState, setGameState] = useState(null);
  const [selectedQuestion, setSelectedQuestion] = useState(null);
  const [questionIndex, setQuestionIndex] = useState({});
  const [clickedQuestions, setClickedQuestions] = useState([]);
  const [selected, setSelected] = useState(false);
  const [selector, setSelector] = useState(selectorUsername);
  const socket = useSocket();
  const { getUsername } = useAuth();
  const username = getUsername();

  // Jeopardy board data example
  // Example data generated by GPT-4o-mini
  const jeopardyPoints = [200, 400, 600, 800, 1000];
  const jeopardyData = {
    categories: [
      {
        name: "History",
        questions: [
          { question: "Who was the first President of the United States?" },
          { question: "In which year did the Titanic sink?" },
          { question: "What was the main cause of World War I?" },
          { question: "Who was the first female Prime Minister of the UK?" },
          { question: "Which ancient civilization built the pyramids?" }
        ]
      },
      {
        name: "Science",
        questions: [
          { question: "What is the chemical symbol for water?" },
          { question: "What planet is known as the Red Planet?" },
          { question: "What gas do plants absorb from the atmosphere?" },
          { question: "What is the powerhouse of the cell?" },
          { question: "What is the most abundant gas in the Earth's atmosphere?" }
        ]
      },
      {
        name: "Literature",
        questions: [
          { question: "Who wrote 'Romeo and Juliet'?" },
          { question: "What is the longest novel ever written?" },
          { question: "Who is the author of '1984'?" },
          { question: "What is the name of the wizarding school in Harry Potter?" },
          { question: "Who wrote 'The Great Gatsby'?" }
        ]
      },
      {
        name: "Geography",
        questions: [
          { question: "What is the capital of France?" },
          { question: "Which river is the longest in the world?" },
          { question: "What is the largest continent?" },
          { question: "Which country is known as the Land of the Rising Sun?" },
          { question: "What is the smallest country in the world?" }
        ]
      },
      {
        name: "Pop Culture",
        questions: [
          { question: "Which pop star is known as the 'Queen of Pop'?" },
          { question: "What movie features the quote, 'There's no place like home'?" },
          { question: "Which animated film features a talking lion named Simba?" },
          { question: "Who played Jack in Titanic?" },
          { question: "What is the name of the fictional city in Batman?" }
        ]
      },
      {
        name: "Sports",
        questions: [
          { question: "Which country hosted the 2016 Summer Olympics?" },
          { question: "Who is known as the 'Great One' in hockey?" },
          { question: "What sport does Serena Williams play?" },
          { question: "Which NFL team has the most Super Bowl wins?" },
          { question: "What is the national sport of Japan?" }
        ]
      }
    ]
  };

  // Converts question indices into question
  const indexToQuestion = (selectedIndex) => {
    const selectedQuestionObj = jeopardyData.categories[selectedIndex['category']].questions[selectedIndex['point']];
    setSelectedQuestion(selectedQuestionObj);
  };

  // Handles clicked question
  const handleSelectedQuestion = (categoryIndex, pointIndex) => {
    let selectedIndex = {};
    selectedIndex['category'] = categoryIndex;
    selectedIndex['point'] = pointIndex;
    console.log(`Selected category: ${selectedIndex['category']}`);
    console.log(`Selected points: ${selectedIndex['point']}`);
    if (selected || username === selectorUsername) {
      socket.emit('selected question', selectedIndex );
    } else {
      console.log("You are not allowed to select a question right now.");
    }
  };
  
  // Handlers socket.on receiving
  useEffect(() => {
    // On who gets choose question
    function onSelector(selectorUsername) {
      console.log(`Selector: ${selectorUsername}`);
      setSelected(username === selectorUsername);
      setSelector(selectorUsername);
    }

    // On what the question is selected
    function onSelectedQuestion(selectedQuestionIndex) {
      setQuestionIndex(selectedQuestionIndex);
      console.log(`Selected category: ${selectedQuestionIndex['category']}`);
      console.log(`Selected points: ${selectedQuestionIndex['point']}`);
      indexToQuestion(selectedQuestionIndex);
    }

    if (socket) {
      socket.on('next question selector', onSelector);
      socket.on('selected question', onSelectedQuestion);

      return () => {
        socket.off('next question selector', onSelector);
        socket.off('selected question', onSelectedQuestion);
      };
    } else {
      console.warn('Jeopardy Board: Socket is not initialized');
    }
  }, [socket]);

  return (
    <Container className="p-4" fluid>
      {/* Display board if not currently in a question */}
      {!selectedQuestion && (
        <React.Fragment>

          {/* Topic headers row */}
          <Row className="g-3 mb-3">
            {jeopardyData.categories.map((category, index) => (
              <Col key={index} className="text-center">
                <Card style={{ minHeight: '100px' }}>
                  <Card.Body>
                    <Card.Title>{category.name}</Card.Title>
                  </Card.Body>
                </Card>
              </Col>
            ))}
          </Row>

          {/* Topic questions with click handlers */}
          <Row xs={6} md={6} className="g-3">
            {Array.from({ length: 5 }, (_, pointIndex) => (
              <React.Fragment key={pointIndex}>
                {jeopardyData.categories.map((category, categoryIndex) => (
                  <Col 
                    key={`${categoryIndex}-${pointIndex}`} 
                    className="clickable-card" 
                    onClick={() => handleSelectedQuestion(categoryIndex, pointIndex)} 
                  >
                    <Card 
                      className="prevent-select" 
                      style={{ minWidth: '80px', minHeight: '100px', padding: '1rem' }}
                    >
                      <Card.Body className='prevent-select'>
                        <Card.Title className="prevent-select text-center">{jeopardyPoints[pointIndex]}</Card.Title>
                      </Card.Body>
                    </Card>
                  </Col>
                ))}
              </React.Fragment>
            ))}
          </Row>
          <a>
            <strong>{selector}</strong> is choosing the question.
          </a>
        </React.Fragment>
      )}

      {/* Display selected question */}
      { selectedQuestion && (
          <>
            <Question selectedQuestion={selectedQuestion} /> 
            <Button onClick={() => {setSelectedQuestion(null)}}>Exit</Button>
          </>
        )
      }
    </Container>
  );
};

export default JeopardyBoard;
