import React from 'react';
import { Container, Row, Col } from 'react-bootstrap';
import Card from 'react-bootstrap/Card';
import './Jeopardy.css';

const JeopardyBoard = () => {
  // Jeopardy board data example
  // Example data generated by GPT-4o-mini
  const jeopardyData = {
    categories: [
      {
        name: "History",
        questions: [
          { points: 200, question: "Who was the first President of the United States?", answer: "George Washington" },
          { points: 400, question: "In which year did the Titanic sink?", answer: "1912" },
          { points: 600, question: "What was the main cause of World War I?", answer: "Assassination of Archduke Franz Ferdinand" },
          { points: 800, question: "Who was the first female Prime Minister of the UK?", answer: "Margaret Thatcher" },
          { points: 1000, question: "Which ancient civilization built the pyramids?", answer: "Egyptians" }
        ]
      },
      {
        name: "Science",
        questions: [
          { points: 200, question: "What is the chemical symbol for water?", answer: "H2O" },
          { points: 400, question: "What planet is known as the Red Planet?", answer: "Mars" },
          { points: 600, question: "What gas do plants absorb from the atmosphere?", answer: "Carbon Dioxide" },
          { points: 800, question: "What is the powerhouse of the cell?", answer: "Mitochondria" },
          { points: 1000, question: "What is the most abundant gas in the Earth's atmosphere?", answer: "Nitrogen" }
        ]
      },
      {
        name: "Literature",
        questions: [
          { points: 200, question: "Who wrote 'Romeo and Juliet'?", answer: "William Shakespeare" },
          { points: 400, question: "What is the longest novel ever written?", answer: "In Search of Lost Time" },
          { points: 600, question: "Who is the author of '1984'?", answer: "George Orwell" },
          { points: 800, question: "What is the name of the wizarding school in Harry Potter?", answer: "Hogwarts" },
          { points: 1000, question: "Who wrote 'The Great Gatsby'?", answer: "F. Scott Fitzgerald" }
        ]
      },
      {
        name: "Geography",
        questions: [
          { points: 200, question: "What is the capital of France?", answer: "Paris" },
          { points: 400, question: "Which river is the longest in the world?", answer: "Nile River" },
          { points: 600, question: "What is the largest continent?", answer: "Asia" },
          { points: 800, question: "Which country is known as the Land of the Rising Sun?", answer: "Japan" },
          { points: 1000, question: "What is the smallest country in the world?", answer: "Vatican City" }
        ]
      },
      {
        name: "Pop Culture",
        questions: [
          { points: 200, question: "Which pop star is known as the 'Queen of Pop'?", answer: "Madonna" },
          { points: 400, question: "What movie features the quote, 'There's no place like home'?", answer: "The Wizard of Oz" },
          { points: 600, question: "Which animated film features a talking lion named Simba?", answer: "The Lion King" },
          { points: 800, question: "Who played Jack in Titanic?", answer: "Leonardo DiCaprio" },
          { points: 1000, question: "What is the name of the fictional city in Batman?", answer: "Gotham City" }
        ]
      },
      {
        name: "Sports",
        questions: [
          { points: 200, question: "Which country hosted the 2016 Summer Olympics?", answer: "Brazil" },
          { points: 400, question: "Who is known as the 'Great One' in hockey?", answer: "Wayne Gretzky" },
          { points: 600, question: "What sport does Serena Williams play?", answer: "Tennis" },
          { points: 800, question: "Which NFL team has the most Super Bowl wins?", answer: "Pittsburgh Steelers" },
          { points: 1000, question: "What is the national sport of Japan?", answer: "Sumo Wrestling" }
        ]
      }
    ]
  };

  return (
    <Container className="p-4" fluid> 
      <Row className="g-3 mb-3">
        {jeopardyData.categories.map((category, index) => (
          <Col key={index} className="text-center">
            <Card style={{ minHeight: '100px' }}>
              <Card.Body>
                <Card.Title>{category.name}</Card.Title>
              </Card.Body>
            </Card>
          </Col>
        ))}
      </Row>
      <Row xs={6} md={6} className="g-3">
        {Array.from({ length: 5 }, (_, pointIndex) => (
          <React.Fragment key={pointIndex}>
            {jeopardyData.categories.map((category, categoryIndex) => (
              <Col key={`${categoryIndex}-${pointIndex}`}>
                <Card className="prevent-select" style={{ minWidth: '80px', minHeight: '100px', padding: '1rem' }} onClick={() => console.log(category.questions[pointIndex])}>
                  <Card.Body className='prevent-select'>
                    <Card.Title className="prevent-select text-center">{category.questions[pointIndex].points}</Card.Title>
                  </Card.Body>
                </Card>
              </Col>
            ))}
          </React.Fragment>
        ))}
      </Row>
    </Container>
  );
};

export default JeopardyBoard;
